## NOTICE: You must use 2 spaces for indention

## Vagrant Settings
vagrant:
  base_vm: ubuntu/trusty64  # base Vagrant image, currently ubuntu/debian only supported
  name: vagrant-dse-51      # default vm name
  memory_size: 6000         # max memory for each VM in mb, recommended = 6000 or more
  cpus: 4                   # number of cpus
  exec_cap: 100             # max CPU utilization cap percentage, recommeded = 100
  ip: 10.10.10.10            # base IP
  hostname: vagrant-dse-51

## VM Settings
vm:
  dse:
    install:
      auto_download: true           # false the correct version below unattended installer must be in installers/dir
      username: foo@example.com     # replace with Datastax Academy/Download username
      password: example             # replace with Datastax Academy/Download password
      version: 5.1.1                # 4.8.1, 4.8.2, 4.8.5...
      force_reinstall: false        # setting to true will mean existing install will be overwritten during reprovision
    cassandra:                      # further settings can be changed in setup/cassandra/cassandra.temp.yaml
      cluster_name: DSE
      snitch: GossipingPropertyFileSnitch
      num_tokens: 32
      seeds: self                   # self = use the vm's IP address making it a single seed
    solr:
      enabled: false
    graph:
      enabled: false
    spark:
      enabled: false
      worker_cores: 3
      worker_memory: 500            # in MBs
    opscenter_agent:
      install: false
      opcenter_ip: vmhost           # localhost = opscenter will run on local comp outside VM and auto-config will be done. Setting IP will disable auto-config
      version: 6.1.0
    start_services: true            # start dse and datastax-agent after install

  studio:
    install: true                   # will attempt to auto-download if not found basedon dse->install logins
    version: 2.0.0
    port: 9091

  ubuntu:
    upgrade_packages: false  # will run aptitude upgrade
    install_packages: "vim sysstat htop"
    install_oracle_jdk: false
    openjdk_packages: "openjdk-8-jdk"
    cassandra_python_driver: false
    swap_disabled: true
