## NOTICE: You must use 2 spaces for indention

## Vagrant Settings
vagrant:
  base_vm: ubuntu/trusty64  # base Vagrant image, currently ubuntu/debian only supported
  name: dse-vagrant         # default vm name
  memory_size: 8000         # max memory for each VM in mb, recommended = 6000 or more
  cpus: 4                   # number of cpus
  exec_cap: 100             # max CPU utilization cap percentage, recommeded = 100
  ip: 10.10.11.10           # base IP
  hostname: dse

## VM Settings
vm:
  dse:
    install:
      auto_download: true           # false the correct version below unattended installer must be in installers/dir
      username: user@example.com    # replace with Datastax Academy/Download username
      password: password            # replace with Datastax Academy/Download password
      version: 4.8.6                # 4.8.1, 4.8.2, 4.8.5...
      force_reinstall: false        # setting to true will mean existing install will be overwritten during reprovision
    cassandra:                      # further settings can be changed in setup/cassandra/cassandra.temp.yaml
      cluster_name: DSE
      snitch: GossipingPropertyFileSnitch
      num_tokens: 64
    agent:
      opcenter_ip: vmhost           # localhost = opscenter will run on local comp outside VM and auto-config will be done. Setting IP will disable auto-config
    solr:
      enabled: false
    spark:
      enabled: false
      worker_cores: 3
      worker_memory: 500            #in mbs

  jupyter:              # See http://jupyter.org/ for more on Jupyter
    enabled: true       # if enabled website can be found at IP address above at the port defined below
    port: 5000

  ubuntu:
    upgrade_packages: false  # will run aptitude upgrade
    install_packages: "vim sysstat git wget htop python-pip python-dev libev4 libev-dev"
    cassandra_python_driver: false
    swap_disabled: true
